# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import management.extras


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='portrait',
            field=models.ImageField(default='/static/base/images/defaults/default-portrait.png', upload_to=management.extras.get_image_path),
        ),
    ]
