# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_students_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Students')),
            ],
        ),
        migrations.CreateModel(
            name='TutorGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_id', models.CharField(max_length=8)),
                ('description', models.TextField(default='No description given.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description given.', max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.TutorGroups'),
        ),
    ]
